PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?entity ?officialName ?startTime ?endTime ?pointInTime WHERE {
  VALUES ?entity {
    wd:Q55902846
  }

  ?entity p:P1448 ?statement .
  ?statement ps:P1448 ?officialName .
  OPTIONAL { ?statement pq:P580 ?startTime . }
  OPTIONAL { ?statement pq:P582 ?endTime . }
  OPTIONAL { ?statement pq:P585 ?pointInTime . }

  FILTER (BOUND(?startTime) || BOUND(?endTime) || BOUND(?pointInTime))
}
