PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?entity ?officialName ?startTime ?endTime ?pointInTime WHERE {
  VALUES ?entity {
    wd:Q55902846 wd:Q33198462 wd:Q3909446 wd:Q77877606 wd:Q16191970 wd:Q111064496 wd:Q111139816 wd:Q8063273
    wd:Q25443487 wd:Q6275139
  }

  ?entity p:P1448 ?statement .
  ?statement ps:P1448 ?officialName .
  OPTIONAL { ?statement pq:P580 ?startTime . }
  OPTIONAL { ?statement pq:P582 ?endTime . }
  OPTIONAL { ?statement pq:P585 ?pointInTime . }

  FILTER (BOUND(?startTime) || BOUND(?endTime) || BOUND(?pointInTime))

  FILTER (
    (
      BOUND(?pointInTime) &&
      ?pointInTime >= "2024-01-01T00:00:00Z"^^xsd:dateTime &&
      ?pointInTime < "2025-01-01T00:00:00Z"^^xsd:dateTime
    )
    ||
    (
      !BOUND(?pointInTime) &&
      (!BOUND(?startTime) || ?startTime < "2025-01-01T00:00:00Z"^^xsd:dateTime) &&
      (!BOUND(?endTime) || ?endTime >= "2024-01-01T00:00:00Z"^^xsd:dateTime)
    )
  )
}
