PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?entity ?mainValue ?relation ?relatedValue WHERE {
  VALUES ?entity {
    wd:Q55902846
  }

  VALUES (?qualifier ?relation) {
    (pq:P155  "follows")
    (pq:P156  "followed by")
    (pq:P1365 "replaces")
    (pq:P1366 "replaced by")
  }

  ?entity p:P361 ?statement .
  ?statement ps:P361 ?mainValue .
  ?statement ?qualifier ?relatedValue .
}
