PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?entity ?position ?startTime WHERE {
  VALUES ?entity {
    wd:Q115043621 wd:Q21573510 wd:Q16358809 wd:Q138031795 wd:Q123876853 wd:Q65566564 wd:Q65587517 wd:Q130620130
    wd:Q4316586 wd:Q20512914
  }

  ?entity p:P39 ?statement .
  ?statement ps:P39 ?position .
  ?statement pq:P580 ?startTime .
  ?statement wikibase:rank wikibase:PreferredRank .
  FILTER NOT EXISTS { ?statement pq:P582 ?endTime . }
}
